import { Hero, NoticeBar } from './hero';
import { RichTextBlock, CardGrid, SplitMedia, Stats, Accordion, LegalDocument, SocialProofBanner } from './layout';
import { LogoMarquee, Gallery, BeforeAfter, VideoEmbed, VideoGrid, FeaturedVideoWork, TabsShowcase } from './media';
import {
  Process,
  CaseStudyGrid,
  CaseStudyCards,
  TestimonialGrid,
  FinalCTA,
  ContactFormBlock,
} from './conversion';
import { landingBlocks, LandingHero, VideoFeature, StatsBar, PillBand, AuditCTA } from './landing';
import {
  testimonialBlocks,
  VideoTestimonials,
  TestimonialCards,
  DividerLabel,
  InlineCTA,
} from './testimonials';
import { contactBlocks, ContactHero, StepsBlock, CalendarEmbed } from './contact';
import {
  serviceBlocks,
  ServicesGrid,
  SplitRow,
  FeatureRow,
  StatsRow,
  LogoStrip,
  ServiceTestimonials,
  ServiceFinalCTA,
} from './services';
import {
  designPrintBlocks,
  PrintHero,
  PrintIntro,
  IconCardGrid,
  PrintProcess,
  ReceiveGrid,
  SignatureProduct,
} from './designPrint';
import { videoServiceBlocks, CommercialPlayer, TwoColumnText, IconFeatureGrid } from './videoservices';
import {
  aboutBlocks,
  StoryBlock,
  InsightQuote,
  ValuesGrid,
  AccordionShowcase,
  VideoReel,
  SimpleQuoteGrid,
} from './about';
import { webDesignBlocks, WebDesignHero, RevealBeforeAfter, CapabilitiesGrid, SimpleIconGrid } from './webdesign';
import { homeBlocks, ShowreelBlock as ShowreelBlockDef, ServiceCarousel, NumberedFeatureGrid } from './home';
import {
  digitalMarketingBlocks,
  DMHero,
  DMAccordion,
  DMSplitMockup,
  DMFeatureRow,
  DMStatsRow,
  DMFinalCTA,
} from './digitalMarketing';

export {
  Hero,
  NoticeBar,
  RichTextBlock,
  LegalDocument,
  SocialProofBanner,
  CardGrid,
  SplitMedia,
  Stats,
  Accordion,
  LogoMarquee,
  Gallery,
  BeforeAfter,
  VideoEmbed,
  VideoGrid,
  FeaturedVideoWork,
  TabsShowcase,
  Process,
  CaseStudyGrid,
  CaseStudyCards,
  TestimonialGrid,
  FinalCTA,
  ContactFormBlock,
  LandingHero,
  VideoFeature,
  StatsBar,
  PillBand,
  AuditCTA,
  VideoTestimonials,
  TestimonialCards,
  DividerLabel,
  InlineCTA,
  ContactHero,
  StepsBlock,
  CalendarEmbed,
  ServicesGrid,
  SplitRow,
  FeatureRow,
  StatsRow,
  LogoStrip,
  ServiceTestimonials,
  ServiceFinalCTA,
  PrintHero,
  PrintIntro,
  IconCardGrid,
  PrintProcess,
  ReceiveGrid,
  SignatureProduct,
  CommercialPlayer,
  TwoColumnText,
  IconFeatureGrid,
  StoryBlock,
  InsightQuote,
  ValuesGrid,
  AccordionShowcase,
  VideoReel,
  SimpleQuoteGrid,
  WebDesignHero,
  RevealBeforeAfter,
  CapabilitiesGrid,
  SimpleIconGrid,
  ShowreelBlockDef as ShowreelBlock,
  ServiceCarousel,
  NumberedFeatureGrid,
  DMHero,
  DMAccordion,
  DMSplitMockup,
  DMFeatureRow,
  DMStatsRow,
  DMFinalCTA,
};

/**
 * Every block an editor can drop onto a page.
 * Order here is the order they appear in the "Add block" menu.
 */
export const allBlocks = [
  Hero,
  NoticeBar,
  SocialProofBanner,
  SplitMedia,
  CardGrid,
  Stats,
  Process,
  TabsShowcase,
  Gallery,
  BeforeAfter,
  VideoEmbed,
  VideoGrid,
  FeaturedVideoWork,
  LogoMarquee,
  CaseStudyCards,
  CaseStudyGrid,
  TestimonialGrid,
  Accordion,
  RichTextBlock,
  LegalDocument,
  ContactFormBlock,
  FinalCTA,
  // Landing-page kit — renders the wc-* / wct-* design systems
  ...landingBlocks,
  ...testimonialBlocks,
  ...contactBlocks,
  ...serviceBlocks,
  ...designPrintBlocks,
  ...videoServiceBlocks,
  ...aboutBlocks,
  ...webDesignBlocks,
  ...homeBlocks,
  ...digitalMarketingBlocks,
];
